services:
  - type: web
    name: nginx-loadbalancer
    env: docker
    plan: free
    dockerfilePath: ./nginx/Dockerfile
    buildContext: ./nginx
    envVars:
      - key: PORT
        value: 8081
